version: '3.8'

services:
  # Nuxt.js приложение
  app:
    container_name: ani-fit-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0
    expose:
      - "3000"
    networks:
      - ani-fit-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  # Nginx для проксирования запросов
  nginx:
    container_name: ani-fit-nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - ani-fit-network
    healthcheck:
      test: ['CMD', 'nginx', '-t']
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ani-fit-network:
    driver: bridge